package com.registro.usuarios.infrastructure.persistence;

import com.registro.usuarios.domain.model.Phone;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Persistence model of one phone of a user. The key is generated by the database: phones are never
 * exposed and are never created outside it. Identity keys grow with insertion order, which keeps
 * the submitted order.
 */
@Entity
@Table(name = "phones")
class PhoneJpaEntity {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id", nullable = false, updatable = false)
  private Long id;

  // The owning side of the association: Hibernate reads it to write user_id, the code never does.
  @SuppressWarnings("UnusedVariable")
  @ManyToOne(fetch = FetchType.LAZY, optional = false)
  @JoinColumn(name = "user_id", nullable = false, updatable = false)
  private UserJpaEntity user;

  @Column(name = "phone_number", nullable = false, length = Phone.NUMBER_MAX_LENGTH)
  private String number;

  @Column(name = "city_code", nullable = false, length = Phone.CODE_MAX_LENGTH)
  private String cityCode;

  @Column(name = "country_code", nullable = false, length = Phone.CODE_MAX_LENGTH)
  private String countryCode;

  /** Required by JPA. */
  protected PhoneJpaEntity() {}

  PhoneJpaEntity(UserJpaEntity user, String number, String cityCode, String countryCode) {
    this.user = user;
    this.number = number;
    this.cityCode = cityCode;
    this.countryCode = countryCode;
  }

  @Override
  public String toString() {
    return "PhoneJpaEntity[id=" + id + "]";
  }
}
