CREATE TABLE IF NOT EXISTS users (
    id            UUID                        NOT NULL,
    name          VARCHAR(255)                NOT NULL,
    email         VARCHAR(254)                NOT NULL,
    password_hash VARCHAR(100)                NOT NULL,
    token         VARCHAR(1024)               NOT NULL,
    is_active     BOOLEAN                     NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    modified_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_login_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS phones (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id      UUID        NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    city_code    VARCHAR(10) NOT NULL,
    country_code VARCHAR(10) NOT NULL,
    CONSTRAINT pk_phones PRIMARY KEY (id),
    CONSTRAINT fk_phones_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_phones_user_id ON phones (user_id);
