package com.registro.usuarios.domain.model;

import java.util.Objects;
import java.util.UUID;

/** Typed identifier of a user, so it cannot be mixed with other strings or UUIDs. */
public record UserId(UUID value) {

  public UserId {
    Objects.requireNonNull(value, "value");
  }

  /** Identifiers are generated by the application, before the row exists. */
  public static UserId generate() {
    return new UserId(UUID.randomUUID());
  }
}
